### ISSUE TITLE
Rename template client to rest-client 

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#1]
## Feature request

Rename the template `client` to `rest-client` to make more clear for an end user that it is a REST template that it will use as core technology.

List available

```
? Available templates  [Use arrows to move, type to filter]
> client
  crud
  custom
  jsp
  rest
```

Remark : We should perhaps rename too the template `rest` to `rest-server`. WDYT ? @metacosm

**Comment by metacosm** [comment]
This is not under `kreate`'s control: the template names come from the generator.
