### ISSUE TITLE
hal component subcommands are confusing

### ISSUE THREAD

**Issue by iocanel** [halkyonio/hal#40]
Going through the demo I see 

`hal component spring-boot` and `hal component create` which is confusing.

`As both pretty much imply `skafolding`. The latter should be `deploy` or something.

**Comment by metacosm** [comment]
> Going through the demo I see
> 
> `hal component spring-boot` and `hal component create` which is confusing.
> 
> As both pretty much imply `skafolding`. The latter should be `deploy` or something.

That's not quite true but I understand the confusion. `create` doesn't scaffold anything, it actually creates the CR and lets the operator know about it. `spring-boot` should probably be renamed `scaffold` at some point, if/when we actually can scaffold something other than Spring Boot apps… :)

**Comment by geoand** [comment]
So is there currently an alternative to `hal component spring-boot`, like `hal component throrntail` or something?

**Comment by geoand** [comment]
Perhaps it could be `hal new-component spring-boot `?

**Comment by metacosm** [comment]
> Perhaps it could be `hal new-component spring-boot `?

If I can help it, no! 😁
I'm thinking that this will go away with the new `create` command, where we could select scaffolding if available at the end of the `create` process.

**Comment by metacosm** [comment]
> So is there currently an alternative to `hal component spring-boot`, like `hal component throrntail` or something?

Ideally, there should be, yes.

**Comment by metacosm** [comment]
> > Perhaps it could be `hal new-component spring-boot `?
> 
> If I can help it, no! 😁
> I'm thinking that this will go away with the new `create` command, where we could select scaffolding if available at the end of the `create` process.

Speaking of which, has anyone tried the new version? https://github.com/halkyonio/hal/pull/32

**Comment by iocanel** [comment]
> Perhaps it could be `hal new-component spring-boot `?

Since, we have `hal component push` I feel that its mandatory to go with `hal component create`.

**Comment by iocanel** [comment]
> > Perhaps it could be `hal new-component spring-boot `?
> 
> Since, we have `hal component push` I feel that its mandatory to go with `hal component create`.

Damn, create is already used!

Maybe `new` or rename `create` to `deploy` which might  be too much.

**Comment by metacosm** [comment]
The new `hal component create` does both operations at once if you want (and the runtime allows it) i.e. it will create a component definition and scaffold the project if you tell it to.

**Comment by iocanel** [comment]
After a long discussion I had with @metacosm on zulip I'd like to share some thoughts.

Scaffolding should have it own command. Something like `hal component scaffold` would be the most descriptive. The command could work interactively or using arguments and allow us to scaffold projects like we do now.

Then' `hal component create` would have a narrower scope and it would be easier to explain what it does.

Some technical concerns around this suggestion, is that we will have to ask the user twice about the runtime, which is bad ux. 

To overcome this issue, we could save information like the runtime, the version etc in a .hal file, that wil be created when we scaffold.

An alternative would be to implement a mechanism to detect the target runtime, using parsing of known project models (maven, gradle, npm).

**Comment by metacosm** [comment]
Opened a new issue for this: #57
