### ISSUE TITLE
Feature: Be more verbose when oc/kubectl report errors

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#41]
## Feature

As oc, kubectl client support to display a more verbose response using the parameter `  -v, --v=0: log level for V logs`, I propose that `hal` also include such option to report more verbose message when by example we can't upload code source as we get an `exit 1: error message`

**Comment by metacosm** [comment]
Fixed by https://github.com/halkyonio/hal/commit/8a3cd12cadd10ea7c2eefa3a38015f6afb23c683
