### ISSUE TITLE
Feature: Improve message display when link can't be created

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#47]
## Feature

Request: Improve the message displayed when link can't be created if by example the secret is not available. We should perhaps tell him to re-play the command, maybe to check if the secret exists instead o this generic message `error completing create: no valid secrets currently exist on the cluster`

```
hal link create -n backend-to-db -t fruit-backend-sb -s postgres-db-config
 ✗  error completing create: no valid secrets currently exist on the cluster
```

Same remark too if the link already exists
```
oc get links
NAME            AGE       STATUS    MESSAGE
backend-to-db   11m       Pending   Waiting for the following resources:
Component: Ready
client-to-backend   1m        Pending   Waiting for the following resources:
Component: Ready

hal link create -n backend-to-db -t fruit-backend-sb -s postgres-db-config
Selected link type: Secret
Selected Change default name: backend-to-db
 ✗  error running create: error communicating with cluster: AlreadyExists
```

**Comment by metacosm** [comment]
For the first issue, this isn't a generic error message. This happens when there are no matching secrets at all on the server. So sure, I could customize it some more but it says exactly what needs to be said.
