### ISSUE TITLE
Add new option/question for the interactive mode when we create a project

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#9]
## Request proposal

Add new option/question for the interactive mode when we create a project to ask when we select `dekorate` if we want to use : 
- K8s/Openshift OR 
- Component
then the generator could add the appropriate deps and java classes

**Comment by metacosm** [comment]
@cmoulliard adding the option on `kreate` is really easy but it won't do anything if support is not implemented on the generator side of things so this is more a generator issue than a `kreate` one.

**Comment by metacosm** [comment]
Actually, thinking about it some more, such an option doesn't make sense for `kreate` as it is i.e. a CLI meant to interact with the component operator so it doesn't make much sense to generate projects without component support…
